import type { ArgKey, ServiceKey } from "./types.js";

export type GargaloDef = {
  id: string;
  /** Título já em forma de hipótese. */
  titulo: string;
  /** 1 (menor) a 3 (maior) — ordena a prioridade de investigação. */
  peso: 1 | 2 | 3;
  impacto: string;
  oportunidade: string;
  melhoria: string;
  estrategiaInicial: string;
  dores: string[];
  servicos: ServiceKey[];
  argumentos: ArgKey[];
  pergunta: string;
};

export const GARGALOS: GargaloDef[] = [
  { id: "sem_estrategia", titulo: "Produz conteúdo, mas não existe estratégia clara.", peso: 3,
    impacto: "pode gerar esforço sem direção: conteúdos que ocupam tempo, mas não constroem posicionamento nem aquisição",
    oportunidade: "definir objetivos, público e pilares para que cada conteúdo tenha função",
    melhoria: "conectar cada publicação a um objetivo (atrair, educar, gerar confiança ou converter)",
    estrategiaInicial: "alinhar objetivo do Instagram e público, definir poucos pilares de conteúdo e um ciclo inicial planejado",
    dores: ["falta_estrategia", "nao_sabe_o_que_postar"], servicos: ["estrategia_conteudo", "planejamento_conteudo", "gestao_mensal_conteudo"], argumentos: ["estrategia", "aquisicao"],
    pergunta: "Hoje existe alguma estratégia por trás dos conteúdos ou vocês vão produzindo conforme aparecem ideias?" },
  { id: "estetica_sem_valor", titulo: "O perfil tem boa apresentação visual, mas comunica pouco valor.", peso: 3,
    impacto: "pode fazer o perfil parecer bonito, mas sem dar ao visitante um motivo claro para seguir ou contratar",
    oportunidade: "transformar a boa base visual em mensagens que deixem claro o valor e o diferencial",
    melhoria: "reforçar nas legendas, na bio e nos destaques o que é oferecido e para quem",
    estrategiaInicial: "revisar posicionamento e bio e definir mensagens-chave para os primeiros conteúdos",
    dores: ["sem_posicionamento", "comunicacao_generica"], servicos: ["posicionamento_digital", "copywriting", "estrategia_conteudo"], argumentos: ["posicionamento", "diferenciacao"],
    pergunta: "Como você explicaria, em uma frase, o que faz o cliente escolher vocês?" },
  { id: "autoridade_nao_convertida", titulo: "Existe autoridade técnica, mas ela não está sendo transformada em conteúdo.", peso: 3,
    impacto: "pode deixar o conhecimento restrito ao atendimento, sem gerar reconhecimento nem novas oportunidades",
    oportunidade: "converter o conhecimento técnico em conteúdos claros, interessantes e fáceis de compartilhar",
    melhoria: "criar conteúdo educativo a partir do que o profissional já explica no dia a dia",
    estrategiaInicial: "levantar temas a partir das dúvidas reais dos clientes e transformá-los em roteiros e carrosséis",
    dores: ["dificuldade_autoridade"], servicos: ["roteiros_video", "carrosseis", "criacao_conteudo", "gestao_mensal_conteudo"], argumentos: ["autoridade", "tempo"],
    pergunta: "Hoje vocês produzem internamente ou alguém ajuda vocês nessa parte?" },
  { id: "pouco_comercial", titulo: "O conteúdo tem pouco direcionamento comercial.", peso: 3,
    impacto: "pode deixar o interesse sem próximo passo, com conteúdo que informa, mas não conduz a uma conversa",
    oportunidade: "incluir chamadas e conteúdos de decisão sem transformar o perfil em vitrine de vendas",
    melhoria: "definir um CTA por conteúdo e um caminho claro até o contato",
    estrategiaInicial: "mapear o funil (descoberta, consideração, conversão) e ajustar chamadas e destaques",
    dores: ["conteudo_sem_clientes", "conteudo_sem_cta"], servicos: ["copywriting", "estrategia_conteudo", "gestao_mensal_conteudo"], argumentos: ["conversao", "aquisicao"],
    pergunta: "Você sente que o Instagram realmente ajuda a gerar oportunidades comerciais?" },
  { id: "institucional", titulo: "O perfil depende muito de posts institucionais.", peso: 2,
    impacto: "pode gerar pouco interesse de quem ainda não conhece o negócio, porque o conteúdo fala mais da empresa do que do que ajuda o cliente",
    oportunidade: "equilibrar o institucional com conteúdo que resolve dúvidas e demonstra conhecimento",
    melhoria: "reduzir posts só sobre a empresa e abrir espaço para conteúdo útil ao cliente",
    estrategiaInicial: "rever o mix de conteúdo e definir pilares que falem das dúvidas do público",
    dores: ["falta_estrategia"], servicos: ["estrategia_conteudo", "planejamento_conteudo", "criacao_conteudo"], argumentos: ["estrategia", "aquisicao"],
    pergunta: "Que tipo de conteúdo você acha que mais aproxima um cliente novo do seu negócio?" },
  { id: "baixa_frequencia", titulo: "Existe baixa frequência ou falta de consistência.", peso: 2,
    impacto: "pode fazer o negócio sumir da lembrança de quem ainda não está pronto para contratar",
    oportunidade: "criar uma rotina viável de publicação, com planejamento antecipado",
    melhoria: "definir uma cadência realista e um calendário mensal",
    estrategiaInicial: "combinar uma frequência sustentável e montar o calendário do primeiro ciclo",
    dores: ["falta_constancia", "perfil_parado", "falta_calendario"], servicos: ["calendario_editorial", "planejamento_conteudo", "gestao_mensal_conteudo"], argumentos: ["consistencia", "tempo"],
    pergunta: "Vocês conseguem manter frequência ou acaba ficando difícil pela rotina?" },
  { id: "oferta_sem_desejo", titulo: "O perfil apresenta serviços, mas não cria desejo.", peso: 2,
    impacto: "pode informar o que é oferecido sem mostrar o que muda na vida ou no negócio do cliente",
    oportunidade: "trabalhar conteúdos de consideração que mostram benefícios, casos e critérios de escolha",
    melhoria: "traduzir cada serviço em benefício e impacto para o cliente",
    estrategiaInicial: "reescrever a comunicação da oferta e criar conteúdos de consideração",
    dores: ["conteudo_sem_clientes"], servicos: ["copywriting", "carrosseis", "estrategia_conteudo"], argumentos: ["conversao", "diferenciacao"],
    pergunta: "O que o cliente costuma dizer que mudou depois de trabalhar com vocês?" },
  { id: "sem_prova_social", titulo: "Há oportunidade de trabalhar mais prova social e cases.", peso: 2,
    impacto: "pode deixar o visitante sem evidências de que o serviço entrega o que promete",
    oportunidade: "organizar depoimentos, bastidores e casos (com autorização) como conteúdo",
    melhoria: "criar uma rotina de captar e publicar provas reais do trabalho",
    estrategiaInicial: "mapear que provas reais existem e como apresentá-las nos destaques e no feed",
    dores: ["dificuldade_autoridade"], servicos: ["criacao_conteudo", "stories", "estrategia_conteudo"], argumentos: ["autoridade", "conversao"],
    pergunta: "Que resultados ou relatos de clientes vocês já têm registrados e autorizados para mostrar?" },
  { id: "bio_fraca", titulo: "A bio pode não deixar claro o que é oferecido nem o próximo passo.", peso: 2,
    impacto: "pode fazer o visitante sair do perfil sem entender o que fazer em seguida",
    oportunidade: "reescrever a bio com valor, especialidade e chamada clara",
    melhoria: "deixar a bio responder: para quem é, o que oferece e o que fazer agora",
    estrategiaInicial: "revisão de bio, link e destaques como primeiro ajuste rápido",
    dores: ["comunicacao_generica", "conteudo_sem_cta"], servicos: ["copywriting", "posicionamento_digital"], argumentos: ["posicionamento", "conversao"],
    pergunta: "Quando alguém chega ao seu perfil, o que você quer que ela faça primeiro?" },
  { id: "sem_humanizacao", titulo: "O perfil pode mostrar pouco as pessoas por trás do negócio.", peso: 1,
    impacto: "pode dificultar a construção de confiança e de vínculo com o público",
    oportunidade: "incluir conteúdos com bastidores, rotina e voz do profissional no nível de exposição confortável",
    melhoria: "definir formatos de humanização adequados ao perfil",
    estrategiaInicial: "combinar o quanto o profissional quer aparecer e planejar formatos a partir disso",
    dores: ["dificuldade_aparecer"], servicos: ["stories", "roteiros_video", "criacao_conteudo"], argumentos: ["marca", "autoridade"],
    pergunta: "Como você se sente em aparecer nos conteúdos? O que incomoda mais?" },
  { id: "reels_baixo", titulo: "O uso de Reels pode estar abaixo do potencial de alcance.", peso: 1,
    impacto: "pode limitar o alcance a quem já segue o perfil",
    oportunidade: "usar Reels como porta de descoberta do conhecimento do profissional",
    melhoria: "planejar roteiros de Reels ligados aos temas de autoridade",
    estrategiaInicial: "definir temas e formatos de Reels e um roteiro-base replicável",
    dores: ["baixo_alcance"], servicos: ["reels", "roteiros_video"], argumentos: ["aquisicao", "autoridade"],
    pergunta: "Vocês já testaram Reels? O que funcionou ou travou?" },
  { id: "stories_sem_estrategia", titulo: "Os Stories podem estar sem estratégia definida.", peso: 1,
    impacto: "pode desperdiçar o canal mais próximo do público já engajado",
    oportunidade: "usar Stories para relacionamento, prova e condução à conversa",
    melhoria: "definir objetivo e sequência para os Stories",
    estrategiaInicial: "planejar sequências simples de Stories ligadas ao calendário do feed",
    dores: ["stories_sem_estrategia"], servicos: ["stories", "planejamento_conteudo"], argumentos: ["conversao", "consistencia"],
    pergunta: "Os Stories têm um objetivo (relacionamento, prova, venda) ou vão saindo conforme dá?" },
  { id: "carrossel_baixo", titulo: "Carrosséis podem estar pouco explorados.", peso: 1,
    impacto: "pode deixar de lado o formato que aprofunda e ajuda na decisão",
    oportunidade: "usar carrosséis para explicar temas técnicos de forma organizada",
    melhoria: "incluir carrosséis educativos nos pilares de conteúdo",
    estrategiaInicial: "escolher temas de carrossel a partir das dúvidas frequentes dos clientes",
    dores: [], servicos: ["carrosseis", "criacao_conteudo"], argumentos: ["autoridade"],
    pergunta: "Quais dúvidas seus clientes repetem com mais frequência?" },
  { id: "baixo_alcance", titulo: "O conteúdo de descoberta parece limitado.", peso: 2,
    impacto: "pode restringir o perfil a quem já o conhece, com pouca chance de novos públicos",
    oportunidade: "criar conteúdos pensados para quem ainda não conhece o negócio",
    melhoria: "equilibrar conteúdo de descoberta com o de consideração e o de conversão",
    estrategiaInicial: "definir temas de descoberta ligados às dúvidas do público que ainda não conhece o negócio",
    dores: ["baixo_alcance"], servicos: ["reels", "estrategia_conteudo", "criacao_conteudo"], argumentos: ["aquisicao", "estrategia"],
    pergunta: "De onde vêm hoje os clientes novos: indicação, busca, redes sociais?" },
  { id: "sem_posicionamento", titulo: "O perfil pode estar sem um posicionamento claro.", peso: 3,
    impacto: "pode levar quem chega a não entender rapidamente para quem é o serviço e o que o diferencia",
    oportunidade: "definir e comunicar um posicionamento claro e coerente",
    melhoria: "escolher uma promessa central e reforçá-la na bio, nos destaques e nos conteúdos",
    estrategiaInicial: "trabalhar posicionamento e narrativa antes de escalar a produção",
    dores: ["sem_posicionamento", "falta_identidade", "comunicacao_generica"], servicos: ["posicionamento_digital", "estrategia_conteudo", "consultoria_conteudo"], argumentos: ["posicionamento", "diferenciacao"],
    pergunta: "Como você explicaria, em uma frase, o que faz o cliente escolher vocês?" },
  { id: "qualidade_baixa", titulo: "A apresentação pode estar abaixo do nível do serviço oferecido.", peso: 2,
    impacto: "pode fazer o perfil comunicar menos valor do que o serviço realmente entrega",
    oportunidade: "elevar padrão visual e de linguagem de forma consistente",
    melhoria: "padronizar identidade visual, capas e formatos",
    estrategiaInicial: "definir padrão visual e de linguagem e aplicá-lo aos próximos conteúdos",
    dores: ["conteudo_pouco_profissional", "baixa_qualidade_videos", "falta_identidade"], servicos: ["branding_conteudo", "criacao_conteudo"], argumentos: ["profissionalizacao", "marca"],
    pergunta: "Você sente que o perfil representa o nível do serviço que vocês entregam?" },
  { id: "cabecalho_fraco", titulo: "O cabeçalho do perfil pode não estar convertendo visita em seguidor ou contato.", peso: 2,
    impacto: "pode fazer quem chega decidir em poucos segundos que não vale seguir ou chamar",
    oportunidade: "ajustar foto, nome, bio, link, destaques e primeiros posts como um conjunto",
    melhoria: "revisar o cabeçalho com um teste simples: um desconhecido entenderia para quem é o perfil só olhando essa área?",
    estrategiaInicial: "revisão rápida do cabeçalho (nome, bio, link, destaques e fixados)",
    dores: ["conteudo_pouco_profissional"], servicos: ["posicionamento_digital", "copywriting", "branding_conteudo"], argumentos: ["profissionalizacao", "posicionamento"],
    pergunta: "Se um desconhecido olhasse só o topo do perfil, ele entenderia para quem é e o que fazer?" },
  { id: "pouco_encontravel", titulo: "O campo de nome pode não estar aproveitando uma palavra-chave que as pessoas pesquisam.", peso: 1,
    impacto: "pode dificultar que o perfil seja encontrado por quem busca o serviço",
    oportunidade: "incluir no nome um termo relacionado à especialidade",
    melhoria: "testar nome no formato Nome | especialidade",
    estrategiaInicial: "ajuste rápido de nome e categoria do perfil",
    dores: ["baixo_alcance"], servicos: ["posicionamento_digital", "copywriting"], argumentos: ["aquisicao", "posicionamento"],
    pergunta: "Como as pessoas costumam encontrar o seu perfil hoje?" },
  { id: "dependencia_indicacao", titulo: "O negócio pode depender quase só de indicação.", peso: 3,
    impacto: "pode limitar o crescimento ao tamanho da rede de contatos",
    oportunidade: "usar o Instagram como vitrine de confiança e canal de novos públicos",
    melhoria: "conectar o conteúdo à jornada de quem foi indicado e de quem ainda não conhece o negócio",
    estrategiaInicial: "definir o papel do Instagram na aquisição e planejar conteúdos para cada etapa",
    dores: ["dependencia_indicacao"], servicos: ["estrategia_conteudo", "gestao_mensal_conteudo"], argumentos: ["aquisicao", "estrategia"],
    pergunta: "Quando alguém é indicado, costuma olhar seu perfil antes de falar com você? O que encontra?" },
];
export const GARGALO_BY_ID = Object.fromEntries(GARGALOS.map((g) => [g.id, g])) as Record<string, (typeof GARGALOS)[number]>;
