import type { ArgKey } from "./types.js";

export type ObjectionDef = {
  key: string;
  rotulo: string;
  padroes: RegExp[];
  porTras: string[];
  pergunta: string;
  resposta: string;
  argumento: { key: ArgKey; frase: string };
  reducaoRisco: string[];
  proximoPasso: string;
};

/**
 * Objeções comuns em serviços de conteúdo. As respostas são perguntas e
 * possibilidades — não afirmam experiência, números nem resultados que não existam.
 */
export const OBJECTIONS: ObjectionDef[] = [
  { key: "eu_mesmo_faco", rotulo: "Eu mesmo faço meu conteúdo",
    padroes: [/eu (mesm[oa]|que) (fa[cç]o|produzo|posto|cuido)/i, /eu (mesm[oa] )?(fa[cç]o|produzo) (meu|o) conte[uú]do/i, /fa[cç]o (tudo )?sozinh[oa]/i],
    porTras: ["gosta de manter a própria voz e o controle", "receio de perder autenticidade", "vê o custo como desnecessário", "pode estar sobrecarregado e não perceber ou não querer admitir"],
    pergunta: "Quando você produz, o que pesa mais: ter ideia, ter tempo ou manter a constância?",
    resposta: "Faz sentido — ninguém conhece o seu conhecimento como você. A ideia não é te substituir, e sim tirar o peso de planejar e produzir, para que a sua voz apareça com mais estratégia e menos esforço. Hoje, o que mais pesa na sua rotina nessa parte?",
    argumento: { key: "tempo", frase: "O conteúdo precisa acontecer sem competir com o seu atendimento." },
    reducaoRisco: ["Você aprova tudo antes de publicar e mantém a sua voz", "Podemos começar só com estratégia e calendário, e você continua gravando"],
    proximoPasso: "Mostrar como fica a rotina com apoio: o que continua com você e o que sai da sua mão." },
  { key: "secretaria_faz", rotulo: "Minha secretária faz",
    padroes: [/(minha|nossa) (secret[aá]ria|recepcionista|assistente|atendente) (que )?(faz|cuida|posta|publica)/i, /secret[aá]ria (que )?(faz|cuida|posta)/i],
    porTras: ["o conteúdo virou tarefa extra de alguém sem foco em estratégia", "receio de desvalorizar quem já faz", "vê a solução atual como suficiente"],
    pergunta: "Ela cuida disso além das funções dela? Existe uma direção definida do que publicar e por quê?",
    resposta: "Ótimo ter alguém que executa. O ponto que vale checar é a estratégia por trás: o que publicar, para quem e com qual objetivo. Posso trabalhar com ela, entregando planejamento e roteiros para que a execução fique mais leve e mais clara — sem tirar o papel dela.",
    argumento: { key: "estrategia", frase: "Produzir conteúdo é diferente de ter uma estratégia de conteúdo." },
    reducaoRisco: ["Complemento a equipe atual, sem substituir ninguém", "Começamos por planejamento e roteiros, e a execução segue como está"],
    proximoPasso: "Entender como ela decide o que publicar e propor uma conversa com as duas partes." },
  { key: "tenho_alguem_posta", rotulo: "Tenho alguém que posta",
    padroes: [/tenho (algu[eé]m|uma pessoa|um (rapaz|menino|profissional)) que (posta|faz|cuida)/i, /j[aá] tenho (algu[eé]m|social media|quem (posta|cuide))/i, /(algu[eé]m|pessoa) (j[aá] )?(posta|cuida) (pra|para) (mim|n[oó]s)/i],
    porTras: ["satisfação com execução, sem cobrar estratégia", "receio de trocar e ter retrabalho", "lealdade a quem já atende"],
    pergunta: "Essa pessoa também define o que publicar e com qual objetivo, ou recebe a pauta pronta?",
    resposta: "Quem posta cuida da execução; o que vale checar é a direção: posicionamento, objetivos e planejamento. Podemos complementar sem trocar ninguém. Hoje quem define os temas e o objetivo de cada conteúdo?",
    argumento: { key: "estrategia", frase: "Cada publicação deveria responder: para quem é e para quê." },
    reducaoRisco: ["Complementar, sem substituição", "Diagnóstico pontual para ver o que está coberto e o que falta"],
    proximoPasso: "Fazer um diagnóstico curto do que existe e do que falta, sem compromisso de troca." },
  { key: "sem_tempo_gravar", rotulo: "Não tenho tempo para gravar",
    padroes: [/n[aã]o tenho tempo (pra|para|de) (gravar|aparecer|fazer v[ií]deo)/i, /sem tempo (pra|para) gravar/i, /n[aã]o (consigo|d[aá]) (tempo )?(pra|para) gravar/i],
    porTras: ["rotina cheia", "imagina gravações longas e complicadas", "perfeccionismo que faz gravar demorar"],
    pergunta: "Qual seria um tempo realista na sua semana para gravar, se tudo já estivesse pronto?",
    resposta: "Entendo. Dá para desenhar um processo em que você grave pouco e de forma organizada: estratégia e roteiro ficam prontos antes, e você só executa. Se preferir, também há formatos que dependem menos de gravação. Qual seria um tempo realista para você?",
    argumento: { key: "tempo", frase: "A ideia não é te substituir; é tirar o peso de planejar e produzir." },
    reducaoRisco: ["Roteiros prontos e objetivos, para gravar sem improvisar", "Formatos alternativos (carrosséis, Stories) para semanas apertadas"],
    proximoPasso: "Definir juntos a janela de gravação e o que dá para produzir sem depender dela." },
  { key: "nao_gosta_aparecer", rotulo: "Não gosto de aparecer",
    padroes: [/n[aã]o gosto de aparecer/i, /tenho (vergonha|timidez)/i, /n[aã]o (quero|curto|gosto) (de )?(aparecer|gravar|ser filmad)/i, /odeio aparecer/i],
    porTras: ["insegurança ou timidez", "preocupação com privacidade", "receio do julgamento"],
    pergunta: "O que mais incomoda: a câmera, a exposição ou não saber o que falar?",
    resposta: "É uma preferência legítima e dá para respeitar. Há formatos que constroem autoridade sem depender de você na câmera, como carrosséis, bastidores, voz e depoimentos. Podemos definir até onde você se sente confortável e ampliar só se e quando quiser.",
    argumento: { key: "autoridade", frase: "Autoridade não é dizer que sabe; é mostrar de um jeito que o outro entenda." },
    reducaoRisco: ["Você define o nível de exposição", "Começar por formatos sem rosto e evoluir se fizer sentido"],
    proximoPasso: "Mapear formatos confortáveis e propor um primeiro ciclo dentro desse limite." },
  { key: "instagram_nao_traz_clientes", rotulo: "Instagram não me traz clientes",
    padroes: [/instagram n[aã]o (me )?(traz|gera|d[aá])/i, /n[aã]o (traz|gera|d[aá]) (cliente|retorno|resultado)/i, /n[aã]o (vejo|tenho) retorno/i, /rede social n[aã]o funciona/i],
    porTras: ["postou sem estratégia e sem medir", "expectativa de resultado rápido", "pode ter tido experiência ruim com agência ou freelancer"],
    pergunta: "O que você já tentou e como acompanhava o resultado?",
    resposta: "Vale entender o motivo antes de concluir que não funciona: quando faltam objetivo, público e chamada para ação, o Instagram tende a virar vitrine. Podemos olhar o que já foi feito e se havia estratégia por trás — e só então decidir se faz sentido investir.",
    argumento: { key: "aquisicao", frase: "Conteúdo bem direcionado prepara o cliente antes de ele falar com você." },
    reducaoRisco: ["Começar com um diagnóstico do que foi feito", "Definir indicadores de sucesso antes de qualquer execução"],
    proximoPasso: "Fazer uma análise curta do histórico do perfil e mostrar hipóteses do que pode estar travando." },
  { key: "ja_tentei_social_media", rotulo: "Já tentei social media",
    padroes: [/j[aá] (tentei|contratei|tive|trabalhei com) (um |uma )?(social media|ag[eê]ncia|freelancer)/i, /j[aá] tive (uma )?experi[eê]ncia (ruim|negativa)/i, /j[aá] (me )?(queimei|paguei) (com|pra)/i],
    porTras: ["experiência anterior sem estratégia ou sem resultados", "desconfiança de promessas", "receio de repetir o gasto"],
    pergunta: "O que faltou na experiência anterior: estratégia, comunicação, qualidade ou resultado?",
    resposta: "Faz sentido a cautela. Para não repetir, começaríamos combinando objetivos e como vamos medir, e você acompanha cada etapa. O que você mais sentiu falta naquela experiência?",
    argumento: { key: "estrategia", frase: "Produzir conteúdo é diferente de ter uma estratégia de conteúdo." },
    reducaoRisco: ["Primeira etapa curta, focada em estratégia", "Critérios de sucesso combinados por escrito", "Revisões em datas definidas"],
    proximoPasso: "Entender o que falhou antes e desenhar uma etapa inicial que evite o mesmo problema." },
  { key: "nao_preciso_postar_tanto", rotulo: "Não preciso postar tanto",
    padroes: [/n[aã]o preciso postar (tanto|todo dia|muito)/i, /n[aã]o (quero|vejo necessidade de) postar (tanto|todo dia)/i, /postar (todo dia|demais) n[aã]o/i],
    porTras: ["associa serviço a volume e a esforço", "pode ter razão: o objetivo talvez não peça frequência alta", "receio de virar obrigação"],
    pergunta: "Qual frequência faz sentido para o seu objetivo com o Instagram?",
    resposta: "Concordo que quantidade não é o objetivo. O ponto é consistência com propósito: menos conteúdos, mas cada um com função. Qual frequência você considera adequada para o que quer alcançar?",
    argumento: { key: "consistencia", frase: "Constância é o que transforma conteúdo em hábito de quem acompanha." },
    reducaoRisco: ["Cadência definida por você e ajustável", "Foco em poucos conteúdos com função clara"],
    proximoPasso: "Definir o objetivo e, a partir dele, a cadência mínima que faz sentido." },
  { key: "cliente_vem_por_indicacao", rotulo: "Meu cliente vem por indicação",
    padroes: [/(meus? )?clientes? (v[eê]m|chega(m)?|vem) (por|de) indica[cç][aã]o/i, /(s[oó]|apenas|somente) (por |de )?indica[cç][aã]o/i, /trabalho (s[oó] )?com indica[cç][aã]o/i, /indica[cç][aã]o (j[aá] )?(basta|resolve|me basta)/i],
    porTras: ["negócio saudável e receio de mexer no que funciona", "indicação como teto de crescimento", "não vê o Instagram como parte da decisão"],
    pergunta: "Quando alguém é indicado, costuma olhar seu perfil antes de falar com você? O que encontra?",
    resposta: "Indicação é um ótimo sinal de confiança. Vale checar se quem é indicado costuma olhar o seu perfil antes de falar com você — nesse caso o Instagram já faz parte da decisão. E ele também pode alcançar públicos além da sua rede de contatos.",
    argumento: { key: "aquisicao", frase: "Indicação é ótimo; o Instagram pode ser a vitrine em que quem foi indicado confere quem você é." },
    reducaoRisco: ["Começar melhorando o que quem é indicado encontra no perfil", "Sem mudar o que já funciona no seu negócio"],
    proximoPasso: "Olhar o perfil como um indicado olharia e listar o que ajudaria a fechar." },
  { key: "esta_caro", rotulo: "Está caro",
    padroes: [/(est[aá]|ficou|achei|[eé]|muito|bem) ?car[oa]/i, /car[oa] demais/i, /n[aã]o cabe no (meu |nosso )?or[cç]amento/i, /pre[cç]o (alto|elevado)/i],
    porTras: ["compara com algo mais barato sem considerar escopo", "não enxerga ainda o retorno que justifica o investimento", "orçamento mais curto que o previsto"],
    pergunta: "Caro em relação a quê — outra proposta, o orçamento que você tinha em mente, ou o resultado que espera?",
    resposta: "Faz sentido olhar com cuidado. Antes de falar de valor, quero ter certeza de que estamos comparando a mesma coisa: escopo, profundidade e acompanhamento. Se me contar com o que está comparando, mostro onde as propostas diferem e ajusto o que fizer sentido para o seu momento.",
    argumento: { key: "estrategia", frase: "Sem objetivo definido, cada postagem é uma aposta isolada; com estratégia, cada uma tem função." },
    reducaoRisco: ["Propor uma fase inicial menor, com escopo claro", "Alinhar por escrito o que está e o que não está incluso"],
    proximoPasso: "Entender a comparação e o orçamento e apresentar uma alternativa de escopo ou de fases." },
  { key: "nao_consigo_videos", rotulo: "Não consigo produzir vídeos",
    padroes: [/n[aã]o (consigo|sei) (produzir|fazer|gravar|editar) v[ií]deo/i, /n[aã]o tenho (equipamento|c[aâ]mera|estrutura) (pra|para) (v[ií]deo|gravar)/i, /v[ií]deo ([eé] |fica )?(dif[ií]cil|complicado)/i],
    porTras: ["acha que exige equipamento ou técnica que não tem", "trava no que falar ou na edição", "perfeccionismo"],
    pergunta: "O que trava: o que falar, como gravar ou a edição?",
    resposta: "Dá para desenhar um formato simples, com roteiro claro e gravação organizada com o que você já tem. Muitas vezes o que falta é clareza do que dizer, e isso o roteiro resolve. Vale começar com pouco e evoluir. O que mais trava hoje?",
    argumento: { key: "tempo", frase: "A ideia não é te substituir; é tirar o peso de planejar e produzir." },
    reducaoRisco: ["Começar com formatos simples", "Roteiro pronto e direção do que gravar"],
    proximoPasso: "Escolher um formato de vídeo simples para testar no primeiro ciclo." },
  { key: "nao_sei_se_consigo_acompanhar", rotulo: "Não sei se vou conseguir acompanhar",
    padroes: [/n[aã]o sei se (vou )?(consigo|conseguir|d[aá]) (acompanhar|dar conta|manter)/i, /(vou|v[aá]) (ficar )?sobrecarregad[oa]/i, /n[aã]o (consigo|vou conseguir) (aprovar|acompanhar|responder)/i],
    porTras: ["receio de virar mais uma obrigação", "medo de aprovações e retornos constantes", "histórico de ficar sem tempo"],
    pergunta: "O que você imagina que seria trabalhoso de acompanhar: aprovar, gravar ou responder mensagens?",
    resposta: "A ideia é o processo ser leve para você: calendário combinado, prazos claros e aprovações objetivas. Se em algum mês a rotina apertar, ajustamos. Qual parte você teme que pese mais?",
    argumento: { key: "tempo", frase: "O conteúdo precisa acontecer sem competir com o seu atendimento." },
    reducaoRisco: ["Fluxo de aprovação simples e com prazos", "Ajuste de ritmo quando a rotina apertar"],
    proximoPasso: "Desenhar o fluxo de acompanhamento com o mínimo de esforço para você." },
  { key: "nao_tenho_material", rotulo: "Não tenho material",
    padroes: [/n[aã]o tenho (material|foto|fotos|v[ií]deo|v[ií]deos|conte[uú]do (pronto|guardado))/i, /(sem|nenhum) material/i, /n[aã]o tenho (o que|nada (pra|para)) (mostrar|postar)/i],
    porTras: ["acha que precisa de fotos e vídeos prontos", "não percebe que o próprio conhecimento é matéria-prima", "receio de ter que produzir muito"],
    pergunta: "O que você já tem de fotos, vídeos, histórias de clientes ou dúvidas frequentes que possamos aproveitar?",
    resposta: "Não é preciso começar com material pronto: o levantamento faz parte do processo. Conhecimento, casos, rotina e perguntas dos clientes viram pauta. O que você já tem de fotos, vídeos ou histórias que possamos aproveitar?",
    argumento: { key: "autoridade", frase: "O conhecimento já existe; falta transformá-lo em conteúdo que trabalhe por você." },
    reducaoRisco: ["Levantamento guiado de material no início", "Começar com o que já existe e complementar aos poucos"],
    proximoPasso: "Fazer um levantamento rápido do que já existe e do que precisa ser produzido." },
];
export const OBJECTION_BY_KEY = Object.fromEntries(OBJECTIONS.map((o) => [o.key, o])) as Record<string, (typeof OBJECTIONS)[number]>;
